apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-broker
  namespace: {{ NAMESPACE }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oidc-broker
  namespace: {{ NAMESPACE }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["oidc-broker"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-broker
  namespace: {{ NAMESPACE }}
subjects:
  - kind: ServiceAccount
    name: oidc-broker
    namespace: {{ NAMESPACE }}
roleRef:
  kind: Role
  name: oidc-broker
  apiGroup: rbac.authorization.k8s.io