apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: oidc-broker
    app.kubernetes.io/version: 1.0.0
  name: oidc-broker
  namespace: {{ NAMESPACE }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 7000
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: oidc-broker
  sessionAffinity: None
  type: ClusterIP